# This is a basic workflow to help you get started with Actions
name: Release
# Controls when the action will run.
on:
  workflow_dispatch:
  push:
    tags:
      - "**"

env:
  REPO_NAME: be-friends
  PAGES_BRANCH: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest

  helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ env.REPO_NAME }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.PAGES_BRANCH }}
          path: ${{ env.PAGES_BRANCH }}
      
      - run: tree .

      - name: package charts
        run: |
          echo ${PWD}
          cd ${{ env.REPO_NAME }}
          echo "TAG: ${GITHUB_REF_NAME}"
          sed -i "s/version:.*/version: ${GITHUB_REF_NAME}/" helm/Chart.yaml
          sed -i "s/appVersion:.*/appVersion: \"${GITHUB_REF_NAME}\"/" helm/Chart.yaml

          helm package helm --destination ../${{ env.PAGES_BRANCH }}
          helm repo index ../${{ env.PAGES_BRANCH }} --url https://${{ github.repository_owner }}.github.io/${{ env.REPO_NAME }}

      - name: push chart to ${{ env.PAGES_BRANCH }}
        run: |
          echo ${PWD}
          cd ${{ env.PAGES_BRANCH }}
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "47479090+cjtim@users.noreply.github.com"
          git add -A
          git commit -m "Update helm chart ${GITHUB_REF_NAME}"
          git push -u origin ${{ env.PAGES_BRANCH }}