name: release-tag
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.PUSH_PAT }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: View package.json
        run: cat package.json
      
      - name: update package.json
        run: |
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "47479090+cjtim@users.noreply.github.com"
          git remote set-url origin https://${{ github.repository_owner }}:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add package.json
          git commit -m "Update package.json version to ${GITHUB_REF_NAME}"
          git push -u origin ${GITHUB_REF_NAME}
